sudo: true
language: c
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libavahi-core-dev libavahi-common-dev libavahi-client-dev libxml2-dev
  - wget https://github.com/lxi/liblxi/archive/master.tar.gz
  - tar -xvf master.tar.gz
  - pushd liblxi-master && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install && popd
before_script: ./autogen.sh
script: ./configure --prefix=/usr && make && sudo make install
